#!/usr/bin/env python

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from icecream import ic
from typer import run

np.set_printoptions(formatter={"float": "{: 0.12f}".format})


def main(filename: str):
    """Plot the results generated by RKKY calculations.

    This variant of the script performs a simplified calculation, where only
    (+z, +z) and (+z, -z) configurations of the spins are considered. This
    does not detect e.g. DMI-like RKKY interactions, but the corresponding
    calculations are much faster when we want to quickly test parameters.
    """

    raw = pd.read_csv(filename, names=["dvec", "s1", "s2", "sep", "E"], skipinitialspace=True)
    raw = raw.sort_values(by=["sep", "s1", "s2", "dvec"])
    ic(raw)

    _, ax1 = plt.subplots()
    plt.xlabel(r"Separation $δ/a$")
    plt.ylabel(r"RKKY interaction $J_{eff}$")
    plt.grid()

    _, ax2 = plt.subplots()
    plt.xlabel(r"Separation $δ/a$")
    plt.ylabel(r"RKKY interaction $J_{eff}$")
    plt.grid()

    for d, df1 in raw.groupby(["dvec"]):
        xs = []
        ys = []
        ls = []
        for δ, df2 in df1.groupby(["sep"]):
            try:
                E_FM = float(df2[(df2["s1"] == "z+") & (df2["s2"] == "z+")].E)
                E_AFM = float(df2[(df2["s1"] == "z+") & (df2["s2"] == "z-")].E)
                J = E_FM - E_AFM

                xs.append(δ)
                ys.append(J)
                ls.append(np.abs(J))
            except:
                pass

        ax1.plot(xs, ys, label=d)
        ax2.plot(xs, ls, label=d)
        ax2.set_yscale("log")

    plt.tight_layout()
    plt.legend()
    plt.show()


if __name__ == "__main__":
    run(main)
