#!/usr/bin/env python

import pandas as pd
from icecream import ic
from typer import run


def main(filename: str):
    """Plot the results generated by RKKY calculations."""

    df = pd.read_csv(filename, names=["s1", "s2", "sep", "E"], skipinitialspace=True)
    ic(df)

    for sep in df.sep.unique():
        E_z_fm = float(df[(df.s1 == "z+") & (df.s2 == "z+") & (df.sep == sep)].E)
        E_z_afm = float(df[(df.s1 == "z+") & (df.s2 == "z-") & (df.sep == sep)].E)
        # E_x_fm = float(df[(df.s1 == "x+") & (df.s2 == "x+") & (df.sep == sep)].E)
        # E_x_afm = float(df[(df.s1 == "x+") & (df.s2 == "x-") & (df.sep == sep)].E)
        print(sep, E_z_fm - E_z_afm)


if __name__ == "__main__":
    run(main)
