version: '3'

tasks:
  default:
    summary: Format and test.
    cmds:
      - clear
      - task: format
      - task: test
  test:
    summary: Unit tests.
    sources:
      - ./bodge/*.py
      - ./tests/*.py
    cmds:
      - python -m pytest tests
  format:
    summary: Code formatters.
    sources:
      - ./**/*.py
    cmds:
      - isort .; echo
      - black .; echo

